# Optimisation in Machine Learning

## Lab Assignment - 4 (6th Sept 2022)
       Ayush Abrol B20AI052

---

In [40]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import yfinance as yf
import cvxopt as cp
import cvxpy as cvx

### Question 1

Looking Daily Close Price Historical Data from 1 July, 2022 to 31 August, 2022 for 3 stocks. (Adani (AWL), MRPL, Bharti Airtel)

In [41]:
data = yf.download("AWL.NS MRPL.NS BHARTIARTL.NS", start="2022-07-01", end="2022-08-31")

[*********************100%***********************]  3 of 3 completed


In [42]:
data.head()

Adj Close                                Close                \
                AWL.NS BHARTIARTL.NS    MRPL.NS      AWL.NS BHARTIARTL.NS   
Date                                                                        
2022-07-01  586.000000    670.469910  81.550003  586.000000    673.450012   
2022-07-04  580.599976    678.882568  78.900002  580.599976    681.900024   
2022-07-05  582.049988    681.421265  77.150002  582.049988    684.450012   
2022-07-06  576.700012    690.879211  70.699997  576.700012    693.950012   
2022-07-07  595.900024    683.760803  72.449997  595.900024    686.799988   

                             High                                  Low  \
              MRPL.NS      AWL.NS BHARTIARTL.NS    MRPL.NS      AWL.NS   
Date                                                                     
2022-07-01  81.550003  590.000000    685.799988  91.250000  558.099976   
2022-07-04  78.900002  594.000000    685.500000  83.500000  575.500000   
2022-07-05  77.150002  592.000000    689.299988  81.449997  581.000000   
2022-07-06  70.699997  587.400024    694.950012  75.500000  574.000000   
2022-07-07  72.449997  599.000000    696.500000  74.199997  580.000000   

                                           Open                           \
           BHARTIARTL.NS    MRPL.NS      AWL.NS BHARTIARTL.NS    MRPL.NS   
Date                                                                       
2022-07-01    666.000000  81.550003  571.000000    684.849976  88.050003   
2022-07-04    666.049988  77.500000  588.849976    670.500000  79.650002   
2022-07-05    680.049988  76.500000  592.000000    683.299988  79.949997   
2022-07-06    684.200012  69.500000  580.250000    684.500000  75.000000   
2022-07-07    685.450012  69.250000  582.000000    692.000000  69.949997   

             Volume                          
             AWL.NS BHARTIARTL.NS   MRPL.NS  
Date                                         
2022-07-01   980990       4488771  26739501  
2022-07-04   649489       4229588  12083139  
2022-07-05   822251       3494504   7568790  
2022-07-06  1011855       4697006  15316422  
2022-07-07  1209630       3485283  11455011

In [43]:
df = data['Adj Close']

In [44]:
df.head()

AWL.NS  BHARTIARTL.NS    MRPL.NS
Date                                            
2022-07-01  586.000000     670.469910  81.550003
2022-07-04  580.599976     678.882568  78.900002
2022-07-05  582.049988     681.421265  77.150002
2022-07-06  576.700012     690.879211  70.699997
2022-07-07  595.900024     683.760803  72.449997

In [45]:
df.shape

(41, 3)

In [46]:
B = df.values
B

array([[586.        , 670.46990967,  81.55000305],
       [580.59997559, 678.88256836,  78.90000153],
       [582.04998779, 681.42126465,  77.15000153],
       [576.70001221, 690.87921143,  70.69999695],
       [595.90002441, 683.76080322,  72.44999695],
       [588.29998779, 692.07391357,  71.94999695],
       [617.65002441, 657.62695312,  71.90000153],
       [648.29998779, 660.06616211,  71.75      ],
       [639.        , 640.65246582,  71.25      ],
       [627.84997559, 638.81066895,  71.75      ],
       [623.70001221, 648.91571045,  71.09999847],
       [623.5       , 660.11590576,  71.55000305],
       [617.25      , 669.92236328,  72.69999695],
       [614.04998779, 667.68231201,  76.30000305],
       [615.        , 675.34820557,  73.5       ],
       [611.54998779, 675.8460083 ,  72.40000153],
       [622.29998779, 675.39801025,  73.25      ],
       [634.04998779, 681.07275391,  73.94999695],
       [645.65002441, 671.91351318,  72.84999847],
       [645.45001221, 663.89910

In [47]:
B.shape

(41, 3)

In [48]:
df.isnull().sum()

AWL.NS           0
BHARTIARTL.NS    0
MRPL.NS          0
dtype: int64

In [49]:
Q = np.cov(B.T)
Q

array([[1939.02202465,  835.31221363,  -32.43026331],
       [ 835.31221363,  805.73026077,   -3.71389027],
       [ -32.43026331,   -3.71389027,    4.9787403 ]])

In [50]:
c = np.array([[0] for i in range (3)])
m = -np.log(np.array([B[-1][i]/B[0][i] for i in range (3)]))
m

array([-0.16648294, -0.08039726,  0.11075693])

In [51]:
a = 0.052 #B20AI052

In [52]:
A = np.column_stack((m, np.negative(np.identity(3, dtype = 'int'))))
b = np.array([-a]+[0]*3)
Aeq = np.array([[1]*3])
beq = np.array([[1]])
A.shape

(3, 4)

In [53]:
A = A.T
A.shape

(4, 3)

In [54]:
sol = cp.solvers.qp(cp.matrix(Q, tc='d'), cp.matrix(c, tc='d'), cp.matrix(A, tc='d'), cp.matrix(b, tc='d'), cp.matrix(Aeq, tc='d'), cp.matrix(beq, tc='d'))
print(sol['x'])

     pcost       dcost       gap    pres   dres
 0:  2.0749e+00  1.4067e+00  9e+00  2e+00  4e+00
 1:  2.0771e+00  2.1055e+00  1e+00  3e-01  5e-01
 2:  2.1939e+00  1.1420e+01  1e+00  3e-01  5e-01
 3:  4.2241e+02  2.3504e+02  5e+02  2e-01  2e-01
 4:  2.7464e+02  2.3540e+02  4e+01  3e-14  8e-14
 5:  2.5685e+02  2.5621e+02  6e-01  4e-16  1e-13
 6:  2.5651e+02  2.5651e+02  6e-03  8e-17  1e-13
 7:  2.5651e+02  2.5651e+02  6e-05  2e-16  3e-13
Optimal solution found.
[ 2.43e-01]
[ 4.99e-01]
[ 2.58e-01]



In [55]:
print("After rounding upto 5 decimal places: ")
for i in range(3):
    print(round(sol['x'][i], 5))

print("The minimum variance portfolio is: ", sol['primal objective'])

After rounding upto 5 decimal places: 
0.24325
0.49864
0.2581
The minimum variance portfolio is:  256.50975307372664


### Question 2

Looking Daily Close Price Historical Data from 1 July, 2022 to 31 August, 2022 for 3 stocks. (Adani (AWL), MRPL, Bharti Airtel, HDFC bank, ITC)

In [56]:
data2 = yf.download("AWL.NS MRPL.NS BHARTIARTL.NS HDFCBANK.NS ITC.NS", start="2022-07-01", end="2022-08-31")

[*********************100%***********************]  5 of 5 completed


In [57]:
data2.head()

Adj Close                                                    \
                AWL.NS BHARTIARTL.NS  HDFCBANK.NS      ITC.NS    MRPL.NS   
Date                                                                       
2022-07-01  586.000000    670.469910  1353.750000  284.350006  81.550003   
2022-07-04  580.599976    678.882568  1355.650024  291.899994  78.900002   
2022-07-05  582.049988    681.421265  1352.599976  286.899994  77.150002   
2022-07-06  576.700012    690.879211  1371.250000  289.299988  70.699997   
2022-07-07  595.900024    683.760803  1395.800049  291.950012  72.449997   

                 Close                                                    ...  \
                AWL.NS BHARTIARTL.NS  HDFCBANK.NS      ITC.NS    MRPL.NS  ...   
Date                                                                      ...   
2022-07-01  586.000000    673.450012  1353.750000  284.350006  81.550003  ...   
2022-07-04  580.599976    681.900024  1355.650024  291.899994  78.900002  ...   
2022-07-05  582.049988    684.450012  1352.599976  286.899994  77.150002  ...   
2022-07-06  576.700012    693.950012  1371.250000  289.299988  70.699997  ...   
2022-07-07  595.900024    686.799988  1395.800049  291.950012  72.449997  ...   

                  Open                                                    \
                AWL.NS BHARTIARTL.NS  HDFCBANK.NS      ITC.NS    MRPL.NS   
Date                                                                       
2022-07-01  571.000000    684.849976  1343.949951  273.500000  88.050003   
2022-07-04  588.849976    670.500000  1353.699951  285.649994  79.650002   
2022-07-05  592.000000    683.299988  1364.000000  293.000000  79.949997   
2022-07-06  580.250000    684.500000  1348.000000  286.100006  75.000000   
2022-07-07  582.000000    692.000000  1380.000000  291.000000  69.949997   

             Volume                                                
             AWL.NS BHARTIARTL.NS HDFCBANK.NS    ITC.NS   MRPL.NS  
Date                                                               
2022-07-01   980990       4488771     5736226  35165665  26739501  
2022-07-04   649489       4229588     4243740  39881736  12083139  
2022-07-05   822251       3494504     7162859  18568655   7568790  
2022-07-06  1011855       4697006     7524539  18292925  15316422  
2022-07-07  1209630       3485283     8871571  13794991  11455011  

[5 rows x 30 columns]

In [58]:
df2 = data2['Adj Close']
df2.head()

AWL.NS  BHARTIARTL.NS  HDFCBANK.NS      ITC.NS    MRPL.NS
Date                                                                     
2022-07-01  586.000000     670.469910  1353.750000  284.350006  81.550003
2022-07-04  580.599976     678.882568  1355.650024  291.899994  78.900002
2022-07-05  582.049988     681.421265  1352.599976  286.899994  77.150002
2022-07-06  576.700012     690.879211  1371.250000  289.299988  70.699997
2022-07-07  595.900024     683.760803  1395.800049  291.950012  72.449997

In [60]:
B2 = df2.values
B2.shape

(41, 5)

In [61]:
df2.isnull().sum()

AWL.NS           0
BHARTIARTL.NS    0
HDFCBANK.NS      0
ITC.NS           0
MRPL.NS          0
dtype: int64

In [62]:
Q2 = np.cov(B2.T)
Q2

array([[1939.02202465,  835.31221363, 1906.71810207,  370.92534766,
         -32.43026331],
       [ 835.31221363,  805.73026077, 1228.35855652,  216.76651072,
          -3.71389027],
       [1906.71810207, 1228.35855652, 2679.57863912,  432.02279289,
         -21.88146428],
       [ 370.92534766,  216.76651072,  432.02279289,   90.30886899,
          -5.56630949],
       [ -32.43026331,   -3.71389027,  -21.88146428,   -5.56630949,
           4.9787403 ]])

In [63]:
c2 = np.array([[0] for i in range (5)])
m2 = -np.log(np.array([B2[-1][i]/B2[0][i] for i in range (5)]))
m2

array([-0.16648294, -0.08039726, -0.0932767 , -0.11967638,  0.11075693])

In [64]:
a = 0.052 #B20AI052

In [65]:
A2 = np.column_stack((m2, np.negative(np.identity(5, dtype = 'int'))))
b2 = np.array([-a]+[0]*5)
Aeq2 = np.array([[1]*5])
beq2 = np.array([[1]])
A2.shape

(5, 6)

In [66]:
A2 = A2.T
A2.shape

(6, 5)

In [67]:
sol = cp.solvers.qp(cp.matrix(Q2, tc='d'), cp.matrix(c2, tc='d'), cp.matrix(A2, tc='d'), cp.matrix(b2, tc='d'), cp.matrix(Aeq2, tc='d'), cp.matrix(beq2, tc='d'))
print(sol['x'])

     pcost       dcost       gap    pres   dres
 0:  1.5853e+00  7.0216e-01  1e+01  3e+00  4e+00
 1:  1.5951e+00  1.3359e+00  1e+00  3e-01  5e-01
 2:  2.9900e+00  4.9181e+00  3e+00  2e-01  3e-01
 3:  3.5158e+00  6.1815e+00  2e+00  1e-01  2e-01
 4:  7.0754e+00  1.6657e+01  6e+00  9e-02  1e-01
 5:  1.9774e+01  2.1503e+01  7e-01  8e-03  1e-02
 6:  2.1569e+01  2.1586e+01  8e-03  7e-05  1e-04
 7:  2.1586e+01  2.1586e+01  8e-05  7e-07  1e-06
 8:  2.1586e+01  2.1586e+01  8e-07  7e-09  1e-08
Optimal solution found.
[-2.69e-09]
[-8.79e-10]
[-1.23e-09]
[ 7.06e-01]
[ 2.94e-01]



In [68]:
print("After rounding upto 5 decimal places: ")
for i in range(5):
    print(round(sol['x'][i], 5))

print("The minimum variance portfolio is: ", sol['primal objective'])

After rounding upto 5 decimal places: 
-0.0
-0.0
-0.0
0.70631
0.29369
The minimum variance portfolio is:  21.586308289756108


### Question 3

Looking Daily Close Price Historical Data from 1 May, 2022 to 31 August, 2022 for 5 stocks. (Adani (AWL), MRPL, Bharti Airtel, HDFC bank, ITC)

In [69]:
data3 = yf.download("AWL.NS MRPL.NS BHARTIARTL.NS HDFCBANK.NS ITC.NS ITC.NS", start="2022-05-01", end="2022-08-31")

[*********************100%***********************]  5 of 5 completed


In [70]:
data3.head()

Adj Close                                                    \
                AWL.NS BHARTIARTL.NS  HDFCBANK.NS      ITC.NS    MRPL.NS   
Date                                                                       
2022-05-02  753.599976    738.069397  1387.566650  257.118866  79.849998   
2022-05-04  715.950012    719.203308  1340.414917  253.796799  78.949997   
2022-05-05  680.200012    715.768555  1337.400024  256.044067  76.750000   
2022-05-06  646.200012    707.107056  1302.456299  260.538666  77.849998   
2022-05-09  613.900024    708.351562  1304.680420  256.923462  73.650002   

                 Close                                                    ...  \
                AWL.NS BHARTIARTL.NS  HDFCBANK.NS      ITC.NS    MRPL.NS  ...   
Date                                                                      ...   
2022-05-02  753.599976    741.349976  1403.699951  263.149994  79.849998  ...   
2022-05-04  715.950012    722.400024  1356.000000  259.750000  78.949997  ...   
2022-05-05  680.200012    718.950012  1352.949951  262.049988  76.750000  ...   
2022-05-06  646.200012    710.250000  1317.599976  266.649994  77.849998  ...   
2022-05-09  613.900024    711.500000  1319.849976  262.950012  73.650002  ...   

                  Open                                                    \
                AWL.NS BHARTIARTL.NS  HDFCBANK.NS      ITC.NS    MRPL.NS   
Date                                                                       
2022-05-02  758.000000    734.000000  1362.050049  258.000000  73.699997   
2022-05-04  745.000000    737.000000  1400.000000  264.000000  80.250000   
2022-05-05  681.000000    726.000000  1375.000000  262.000000  79.800003   
2022-05-06  646.200012    711.250000  1330.000000  259.000000  75.000000   
2022-05-09  613.900024    706.099976  1300.000000  266.149994  78.000000   

              Volume                                                
              AWL.NS BHARTIARTL.NS HDFCBANK.NS    ITC.NS   MRPL.NS  
Date                                                                
2022-05-02  11750710       3938533     9747158  18965820  28382804  
2022-05-04  12572099       6785271    14527958  25951999  31101904  
2022-05-05   1088061       4836692     8931456  17932895  16541802  
2022-05-06   2695071       5912312    13365634  34490123  16431211  
2022-05-09    624222       4819274    16381217  21403710  11232270  

[5 rows x 30 columns]

In [71]:
df3 = data3['Adj Close']
df3.head()

AWL.NS  BHARTIARTL.NS  HDFCBANK.NS      ITC.NS    MRPL.NS
Date                                                                     
2022-05-02  753.599976     738.069397  1387.566650  257.118866  79.849998
2022-05-04  715.950012     719.203308  1340.414917  253.796799  78.949997
2022-05-05  680.200012     715.768555  1337.400024  256.044067  76.750000
2022-05-06  646.200012     707.107056  1302.456299  260.538666  77.849998
2022-05-09  613.900024     708.351562  1304.680420  256.923462  73.650002

In [72]:
B3 = df3.values
B3.shape

(84, 5)

In [73]:
df3.isnull().sum()

AWL.NS           0
BHARTIARTL.NS    0
HDFCBANK.NS      0
ITC.NS           0
MRPL.NS          0
dtype: int64

In [74]:
Q3 = np.cov(B3.T)
Q3

array([[2452.2902991 ,  714.11017694, 1676.98812513,  404.36271559,
         -72.956027  ],
       [ 714.11017694,  653.68766982,  844.15702526,  153.26307173,
         -99.5720104 ],
       [1676.98812513,  844.15702526, 3611.93628562, 1091.80878188,
        -279.65958252],
       [ 404.36271559,  153.26307173, 1091.80878188,  452.05777422,
        -113.84342014],
       [ -72.956027  ,  -99.5720104 , -279.65958252, -113.84342014,
         139.95047009]])

In [75]:
c3 = np.array([[0] for i in range (5)])
m3 = -np.log(np.array([B3[-1][i]/B3[0][i] for i in range (5)]))
m3

array([ 0.08505896,  0.01566177, -0.06860362, -0.22034378,  0.08969041])

In [76]:
a = 0.052 #B20AI052

In [77]:
A3 = np.column_stack((m3, np.negative(np.identity(5, dtype = 'int'))))
b3 = np.array([-a]+[0]*5)
Aeq3 = np.array([[1]*5])
beq3 = np.array([[1]])
A3.shape

(5, 6)

In [78]:
A3 = A3.T
A3.shape

(6, 5)

In [79]:
sol = cp.solvers.qp(cp.matrix(Q3, tc='d'), cp.matrix(c3, tc='d'), cp.matrix(A3, tc='d'), cp.matrix(b3, tc='d'), cp.matrix(Aeq3, tc='d'), cp.matrix(beq3, tc='d'))
print(sol['x'])

     pcost       dcost       gap    pres   dres
 0:  1.6445e+01  1.5475e+01  1e+01  3e+00  3e+00
 1:  1.6445e+01  1.6009e+01  1e+00  3e-01  4e-01
 2:  2.7065e+01  2.2941e+01  1e+01  2e-01  2e-01
 3:  3.2544e+01  3.5986e+01  4e+01  1e-01  2e-01
 4:  3.8178e+01  3.8499e+01  2e+00  6e-03  7e-03
 5:  3.8734e+01  3.8735e+01  2e-02  6e-05  7e-05
 6:  3.8739e+01  3.8739e+01  2e-04  6e-07  7e-07
 7:  3.8739e+01  3.8739e+01  2e-06  6e-09  7e-09
Optimal solution found.
[-1.91e-09]
[ 4.62e-02]
[-2.00e-09]
[ 4.46e-01]
[ 5.08e-01]



In [80]:
print("After rounding upto 5 decimal places: ")
for i in range(5):
    print(round(sol['x'][i], 5))

print("The minimum variance portfolio is: ", sol['primal objective'])

After rounding upto 5 decimal places: 
-0.0
0.04618
-0.0
0.44599
0.50783
The minimum variance portfolio is:  38.738999095674885


---