# Optimistaion for Machine Learning 

    Ayush Abrol B20AI052

---

In [2]:
from gekko import GEKKO
import numpy as np

### Question 1

In [3]:
# max 9x1 + 5x2 + 6x3 + 4x4
# s.t 6x1 + 3x2 + 5x3 + 2x4 ≤ 10
# x1 + x4 ≤ 1
# −x1 + x3 ≤ 0
# −x2 + x4 ≤ 0
# x1,2,3,4 ∈ {0, 1}

In [6]:
m = GEKKO(remote=False)
c = array([[9],[5],[6],[4]])
A = array([[6,3,5,2],[1,0,0,1],[-1,0,1,0],[0,-1,0,1]])
b = array([[9],[1],[0],[0]])
z = m.Array(m.Var,4,integer=True,lb=0,ub=1)
#z1=m.array(m.Var,1,integer=False,lb=0,ub=1)
m.qobj(c,x=z,otype='max')
m.axb(A,b,x=z,etype='<=')
#m.axb(A,b,x=z1,type='<=')
m.options.SOLVER = 1
m.solve()
print('Objective: ', m.options.OBJFCNVAL)
print(z)
print('x: ', z[0].value[0],z[1].value[0],z[2].value[0],z[3].value[0])
print('y: ', z[1].value[0])

A
[[ 6.  3.  5.  2.]
 [ 1.  0.  0.  1.]
 [-1.  0.  1.  0.]
 [ 0. -1.  0.  1.]]
b
[[9. 1. 0. 0.]]
 ----------------------------------------------------------------
 APMonitor, Version 1.0.0
 APMonitor Optimization Suite
 ----------------------------------------------------------------
 
 
 --------- APM Model Size ------------
 Each time step contains
   Objects      :  2
   Constants    :  0
   Variables    :  4
   Intermediates:  0
   Connections  :  8
   Equations    :  0
   Residuals    :  0
 
 Number of state variables:    4
 Number of total equations: -  4
 Number of slack variables: -  0
 ---------------------------------------
 Degrees of freedom       :    0
 
 ----------------------------------------------
 Steady State Optimization with APOPT Solver
 ----------------------------------------------
Iter:     1 I:  0 Tm:     -0.00 NLPi:    1 Dpth:    0 Lvs:    3 Obj: -1.39E+01 Gap:       NaN
--Integer Solution:  -1.40E+01 Lowest Leaf:  -1.40E+01 Gap:   0.00E+00
Iter:     2 I:  0

### Question 2

In [7]:
# max 7x1 + 3x2
# s.t 5x1 + 7x2 ≤ 27
# 4x1 + x2 ≤ 14
# 3x1 − 2x2 ≤ 9
# x1, x2 ≥ 0
# x1Integer