##Optimization for Machine Learning CSL4010

### LAB Assignment 3B

Navlika Singh (B20AI025)

In [ ]:
#mount on google colab
from google.colab import drive
drive.mount("/gdrive")
%cd /gdrive

Mounted at /gdrive
/gdrive


In [ ]:
#required imports
import numpy as np
import pandas as pd
import cvxopt as cp
import math

QUESTION 1

In [ ]:
#QP
Q = np.array([
        [2, 1, 0], 
        [1, 2, 1], 
        [0, 1, 2]
    ])

p = np.array([0, 0, 0])
h = np.array([[-0.25], [0], [0], [0]])
G = np.array([
    [-0.4, -0.4, -0.8],
    [-1, 0, 0],
    [0, -1, 0],
    [0, 0, -1]
])
A_eq = np.array([
        [1, 1, 1]
])
b_eq = np.array(
    [
    [1]
    ]
)

result = cp.solvers.qp(
    cp.matrix(Q, tc='d'),
    cp.matrix(p, tc='d'),
    cp.matrix(G, tc='d'),
    cp.matrix(h, tc='d'),
    cp.matrix(A_eq, tc='d'),
    cp.matrix(b_eq, tc='d')
)

print("Answer:")
print(result['x'], result['primal objective'])
print(result["primal objective"])

     pcost       dcost       gap    pres   dres
 0:  5.2583e-01 -8.6018e-01  1e+00  6e-17  4e+00
 1:  5.1550e-01  4.5454e-01  6e-02  1e-16  2e-01
 2:  5.0254e-01  4.9688e-01  6e-03  2e-16  4e-03
 3:  5.0036e-01  4.9958e-01  8e-04  1e-16  2e-16
 4:  5.0005e-01  4.9994e-01  1e-04  2e-16  7e-17
 5:  5.0001e-01  4.9999e-01  2e-05  6e-17  9e-17
 6:  5.0000e-01  5.0000e-01  2e-06  8e-17  7e-17
 7:  5.0000e-01  5.0000e-01  3e-07  2e-16  4e-17
Optimal solution found.
Answer:
[ 5.00e-01]
[ 5.42e-04]
[ 5.00e-01]
 0.5000001467290747
0.5000001467290747


QUESTION 2

In [ ]:
#import and display data
data_2 = pd.read_csv("/gdrive/MyDrive/OML/LAB_ASSIGNMENT_3B/Two-Stocks.csv")
data_2

Tesla       Apple
0   244.523331  154.300003
1   245.423340  148.970001
2   253.163330  146.059998
3   258.130005  146.919998
4   258.406677  142.649994
5   261.829987  142.899994
6   281.010010  144.839996
7   303.226654  148.690002
8   371.333344  149.800003
9   407.363342  151.279999
10  344.473328  149.990005
11  379.019989  160.550003
12  360.640015  156.809998
13  338.323334  161.839996
14  339.010010  179.449997
15  310.856659  171.139999
16  355.666656  176.279999
17  352.260010  177.570007
18  342.320007  172.169998
19  349.869995  173.070007
20  314.633331  162.410004
21  282.116669  170.330002
22  307.773346  172.389999
23  286.666656  168.639999
24  285.660004  167.300003
25  269.956665  164.850006
26  279.429993  163.169998
27  265.116669  154.729996
28  301.796661  163.979996
29  336.880005  174.720001
30  361.529999  174.309998
31  341.829987  170.089996
32  328.333344  165.289993
33  335.016663  161.789993
34  290.253326  157.649994
35  288.549988  157.279999
36  256.529999  147.110001
37  221.300003  137.589996
38  253.210007  149.639999
39  234.516663  145.380005
40  232.229996  137.130005
41  216.759995  131.559998
42  245.706665  141.660004
43  227.263336  138.929993
44  250.763336  147.039993
45  240.066666  150.169998
46  272.243347  154.089996
47  297.149994  162.509995
48  288.170013  165.350006
49  300.029999  172.100006
50  296.666656  171.520004
51  288.089996  163.619995
52  284.820007  161.380005

In [ ]:
#covariance matrix
Q = data_2.cov().to_numpy()
print("Covariance Matrix:", Q)

Covariance Matrix: [[2082.86782749  349.74814771]
 [ 349.74814771  148.91724703]]


In [ ]:
#m matrix
M = np.array([math.log(data_2["Tesla"][data_2.shape[0] - 1]/data_2["Tesla"][0]), math.log(data_2["Apple"][data_2.shape[0] - 1]/data_2["Apple"][0])])
print("M:", M)

M: [0.1525467  0.04486308]


In [ ]:
#QP
p = np.array([0, 0])
h = np.array([[-0.025], [0], [0]])
G = np.array([
    [-0.1525467, -0.04486308],
    [-1, 0],
    [0, -1],
])
A_eq = np.array([
        [1, 1]
])
b_eq = np.array(
    [
    [1]
    ]
)

result = cp.solvers.qp(
    cp.matrix(Q, tc='d'),
    cp.matrix(p, tc='d'),
    cp.matrix(G, tc='d'),
    cp.matrix(h, tc='d'),
    cp.matrix(A_eq, tc='d'),
    cp.matrix(b_eq, tc='d')
)

print("Answer:")
print(result['x'], result['primal objective'])
print(result["primal objective"])

     pcost       dcost       gap    pres   dres
 0:  6.1298e+01  6.0450e+01  7e+00  2e+00  3e+00
 1:  6.1300e+01  6.1261e+01  8e-01  2e-01  4e-01
 2:  1.0297e+02  6.6207e+01  4e+01  3e-16  6e-14
 3:  7.7991e+01  7.3892e+01  4e+00  1e-16  9e-14
 4:  7.4540e+01  7.4453e+01  9e-02  9e-19  3e-14
 5:  7.4459e+01  7.4459e+01  9e-04  2e-16  6e-14
 6:  7.4459e+01  7.4459e+01  9e-06  1e-16  6e-14
Optimal solution found.
Answer:
[ 4.07e-08]
[ 1.00e+00]
 74.45863168515056
74.45863168515056


QUESTION 3

In [ ]:
#import and display data
data_3 = pd.read_csv("/gdrive/MyDrive/OML/LAB_ASSIGNMENT_3B/Four-Stocks.csv")
data_3

Google       Tesla      Amazon       Apple
0   144.774994  244.523331  173.902496  154.300003
1   141.921005  245.423340  173.457504  148.970001
2   141.463501  253.163330  173.126007  146.059998
3   142.632996  258.130005  171.276001  146.919998
4   136.462494  258.406677  164.162994  142.649994
5   140.056000  261.829987  164.431000  142.899994
6   141.675003  281.010010  170.451004  144.839996
7   138.625000  303.226654  166.777496  148.690002
8   148.270493  371.333344  168.621506  149.800003
9   149.240997  407.363342  175.949493  151.279999
10  149.645493  344.473328  176.257507  149.990005
11  149.952499  379.019989  183.828506  160.550003
12  142.806000  360.640015  175.227997  156.809998
13  142.520493  338.323334  169.489502  161.839996
14  148.675003  339.010010  172.212006  179.449997
15  142.802994  310.856659  170.017502  171.139999
16  147.142502  355.666656  171.068497  176.279999
17  144.679504  352.260010  166.716995  177.570007
18  137.004501  342.320007  162.554001  172.169998
19  139.786499  349.869995  162.138000  173.070007
20  130.091995  314.633331  142.643005  162.410004
21  133.289505  282.116669  143.977997  170.330002
22  143.016006  307.773346  157.639496  172.389999
23  134.130005  286.666656  153.293503  168.639999
24  130.467499  285.660004  152.601501  167.300003
25  134.519501  269.956665  153.788498  164.850006
26  132.121994  279.429993  145.641006  163.169998
27  130.475494  265.116669  145.524506  154.729996
28  136.801498  301.796661  161.250504  163.979996
29  141.521500  336.880005  164.773499  174.720001
30  140.699997  361.529999  163.559998  174.309998
31  134.010498  341.829987  154.460495  170.089996
32  127.252998  328.333344  151.706497  165.289993
33  119.613998  335.016663  144.350006  161.789993
34  114.966499  290.253326  124.281502  157.649994
35  115.660004  288.549988  114.772499  157.279999
36  116.515503  256.529999  113.055000  147.110001
37  109.313004  221.300003  107.591003  137.589996
38  112.799004  253.210007  115.146500  149.639999
39  114.564003  234.516663  122.349998  145.380005
40  111.427498  232.229996  109.650002  137.130005
41  107.865501  216.759995  106.220001  131.559998
42  118.538002  245.706665  116.459999  141.660004
43  109.081001  227.263336  109.559998  138.929993
44  120.168503  250.763336  115.540001  147.039993
45  112.766998  240.066666  113.550003  150.169998
46  108.360001  272.243347  122.419998  154.089996
47  116.639999  297.149994  134.949997  162.509995
48  118.220001  288.170013  140.800003  165.350006
49  122.650002  300.029999  143.550003  172.100006
50  118.120003  296.666656  138.229996  171.520004
51  111.300003  288.089996  130.750000  163.619995
52  110.339996  284.820007  129.789993  161.380005

In [ ]:
#covariance matrix
Q = data_3.cov().to_numpy()
print("Covariance Matrix:", Q)

Covariance Matrix: [[ 186.78060121  388.4930077   298.52156555   59.18886571]
 [ 388.4930077  2082.86782749  674.57495437  349.74814771]
 [ 298.52156555  674.57495437  529.66181033  113.02303208]
 [  59.18886571  349.74814771  113.02303208  148.91724703]]


In [ ]:
#m matrix
M = np.array([math.log(data_3["Google"][data_3.shape[0] - 1]/data_3["Google"][0]),
              math.log(data_3["Tesla"][data_3.shape[0] - 1]/data_3["Tesla"][0]),
              math.log(data_3["Amazon"][data_3.shape[0] - 1]/data_3["Amazon"][0]),
              math.log(data_3["Apple"][data_3.shape[0] - 1]/data_3["Apple"][0])])
print("M:", M)

M: [-0.2716143   0.1525467  -0.29257707  0.04486308]


In [ ]:
#QP
p = np.array([0, 0, 0, 0])
h = np.array([[-0.25], [0], [0], [0], [0]])
G = np.array([
    [0.2716143, -0.1525467, 0.29257707, -0.04486308],
    [-1, 0, 0, 0],
    [0, -1, 0, 0],
    [0, 0, -1, 0],
    [0, 0, 0, -1]
])
A_eq = np.array([
        [1, 1, 1, 1]
])
b_eq = np.array(
    [
    [1]
    ]
)

result = cp.solvers.qp(
    cp.matrix(Q, tc='d'),
    cp.matrix(p, tc='d'),
    cp.matrix(G, tc='d'),
    cp.matrix(h, tc='d'),
    cp.matrix(A_eq, tc='d'),
    cp.matrix(b_eq, tc='d')
)

print("Answer:")
print(result['x'], result['primal objective'])
print(result["primal objective"])

     pcost       dcost       gap    pres   dres
 0:  2.1703e+01  2.2430e+01  1e+01  3e+00  4e+00
 1:  2.1817e+01  2.4916e+01  4e+00  1e+00  1e+00
 2:  2.5334e+01  3.9086e+01  5e+00  9e-01  1e+00
 3:  1.3036e+02  1.7362e+02  2e+02  7e-01  8e-01
 4:  1.1787e+02  1.8766e+02  2e+02  7e-01  8e-01
 5:  1.1099e+02  2.4764e+02  1e+02  4e-01  5e-01
 6:  1.1211e+02  5.8757e+02  6e+01  3e-01  3e-01
 7:  9.0891e+02  2.4943e+03  9e+02  2e-01  3e-01
 8:  1.2363e+03  2.7745e+03  9e+02  2e-01  2e-01
 9:  6.8101e+02  4.2485e+03  1e+03  2e-01  2e-01
10:  1.2878e+03  1.0049e+04  2e+02  1e-01  1e-01
11:  1.2777e+03  9.9187e+04  1e+03  1e-01  1e-01
12:  1.2845e+03  3.5744e+06  3e+04  1e-01  1e-01
13:  1.2938e+03  4.7822e+08  2e+05  1e-01  1e-01
14:  1.2945e+03  9.5242e+11  8e+06  1e-01  1e-01
15:  1.2945e+03  1.1148e+17  1e+10  1e-01  8e+01
16:  1.2945e+03  1.2778e+24  1e+15  1e-01  2e+09
17:  1.2945e+03  1.3316e+33  2e+22  1e-01  5e+17
18:  1.2945e+03  6.5695e+43  3e+32  1e-01  4e+28
19:  1.2945e+03  6.83