In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
data = pd.read_excel('3 columns.xls')
data

area  bedrooms    price
0   3050         3  3920000
1   3100         2  2135000
2   4320         3  4690000
3   3060         3  3465000
4   2575         2  3290000
..   ...       ...      ...
95  6600         4  9100000
96  2145         3  4200000
97  5200         4  2852500
98  4410         2  4200000
99  8400         3  5250000

[100 rows x 3 columns]

In [4]:
# We need to find the best fitting plane z = a1x + a2y + a3
# We can use the least squares method to find the best fitting plane

In [5]:
B = data.values
B

array([[    3050,        3,  3920000],
       [    3100,        2,  2135000],
       [    4320,        3,  4690000],
       [    3060,        3,  3465000],
       [    2575,        2,  3290000],
       [    8960,        4, 12250000],
       [    6600,        3,  6090000],
       [    3800,        2,  3045000],
       [    4992,        3,  4060000],
       [    2400,        3,  1767150],
       [    3512,        2,  3500000],
       [    4500,        3,  3990000],
       [    5400,        3,  4025000],
       [    3180,        2,  2310000],
       [    4040,        2,  4095000],
       [    3180,        4,  3290000],
       [    2817,        4,  5495000],
       [    6615,        3,  2940000],
       [    6540,        3,  5950000],
       [    3520,        2,  4515000],
       [    4500,        2,  3080000],
       [    5700,        3,  6650000],
       [    4840,        2,  2450000],
       [    7250,        3,  4200000],
       [    3090,        3,  3010000],
       [    3745,        

In [6]:
x = B[:,0]
y = B[:,1]
z = B[:,2]

In [7]:
A = np.vstack([x, y, np.ones(len(x))]).T
A

array([[3.050e+03, 3.000e+00, 1.000e+00],
       [3.100e+03, 2.000e+00, 1.000e+00],
       [4.320e+03, 3.000e+00, 1.000e+00],
       [3.060e+03, 3.000e+00, 1.000e+00],
       [2.575e+03, 2.000e+00, 1.000e+00],
       [8.960e+03, 4.000e+00, 1.000e+00],
       [6.600e+03, 3.000e+00, 1.000e+00],
       [3.800e+03, 2.000e+00, 1.000e+00],
       [4.992e+03, 3.000e+00, 1.000e+00],
       [2.400e+03, 3.000e+00, 1.000e+00],
       [3.512e+03, 2.000e+00, 1.000e+00],
       [4.500e+03, 3.000e+00, 1.000e+00],
       [5.400e+03, 3.000e+00, 1.000e+00],
       [3.180e+03, 2.000e+00, 1.000e+00],
       [4.040e+03, 2.000e+00, 1.000e+00],
       [3.180e+03, 4.000e+00, 1.000e+00],
       [2.817e+03, 4.000e+00, 1.000e+00],
       [6.615e+03, 3.000e+00, 1.000e+00],
       [6.540e+03, 3.000e+00, 1.000e+00],
       [3.520e+03, 2.000e+00, 1.000e+00],
       [4.500e+03, 2.000e+00, 1.000e+00],
       [5.700e+03, 3.000e+00, 1.000e+00],
       [4.840e+03, 2.000e+00, 1.000e+00],
       [7.250e+03, 3.000e+00, 1.00

In [9]:
beta = np.dot(np.linalg.inv(np.dot(A.T,A)),np.dot(A.T,z.T))
print(beta)

[4.11335474e+02 8.32351204e+05 1.40790447e+05]
